# Saigon Jekyll Theme Config
permalink: /:categories/:title/
author_img_name_path: "/images/users/user.jpg"

google_analytics_code: "UA-142289661-1"


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url:  # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # 'soal' # the subpath of your site, e.g. /blog

title: 'SOAL'
full_name: 'Shephards of Abundant Living'
copyright_year: "2019"
email: clboulter@shaw.ca

logo: /assets/images/soal220.png

description: >
  Shephards of Abundant Living

# SEO
#image: /assets/images/open_graph_image.png
google_analytics: # UA-XXXXXXXX-XX -> https://minimalanalytics.com/


collections:
  rooms:
    listed: true
    output: true
    permalink: /:collection/:title
  artisan:
    listed: true
    output: true
    permalink: /:collection/:title
  gallery:
    listed: true
    output: true
    permalink: /:collection/:title
  events:
    listed: true
    output: true
    permalink: /:collection/:title
  pages:
    listed: true
    output: true
    permalink: /:title


defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      priority: 5
  # _gallery
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "profile"
      image: "/assets/images/soal220.png"
      images:
        - "/assets/images/bigs/1.jpg"
        - "/assets/images/bigs/2.jpg"
        - "/assets/images/bigs/3.jpg"
        - "/assets/images/bigs/4.jpg"
      description: >
        This is a sample description to aid in formatting the site.
        Add your own on <a href="https://www.soalhouse.ca/admin">the Soalhouse Admin Panel.</a>
  # _artisan
  - scope:
      path: ""
      type: "artisan"
    values:
      layout: "artisan"
      image: "/assets/images/soal150.svg"
  # _events
  - scope:
      path: ""
      type: "events"
    values:
      layout: default
      teaser_image: "/assets/images/events/party-hat.png"
      description: ""
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache


sidebar:
  - gradient-light: #450003
  - gradient-dark: #771100


include:
  ["_pages"]

exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
  - assets/_sass/unused.scss
