# Saigon Jekyll Theme Config
permalink: /:categories/:title/
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
google_analytics_code: ""


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: 'https://ashcatcher.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # 'soal' # the subpath of your site, e.g. /blog

title: 'SOAL'
full_name: 'Shephards of Abundant Living'
copyright_year: "2019"
email: clboulter@shaw.ca

logo: /assets/images/soal220.png

description: >
  <p>Based upon the wonderful <a href="https://github.com/ginfuru/Flightdeck" target="_blank">Flightdeck Jekyll Starter</a></p>
  <p>Built using graphical assets from <a href="https://github.com/hoffli/saigon-jekyll-theme/">Saigon Masonry Jekyll Theme</a></p>
  <p>The color combination used here comes from <a href="http://clrs.cc" target="_blank">CLRS</a></p>

# SEO
#image: /assets/images/open_graph_image.png
google_analytics: # UA-XXXXXXXX-XX -> https://minimalanalytics.com/

# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
