backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "blog"
    label: "Post"
    folder: "_posts/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document. Specified in the front-matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/assets/images/blog/post1.jpg"
        media_library:
          config:
            multiple: true

  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Permalink", name: "permalink", widget: "string", default: "{{slug}}" }
      - { label: "Title", name: "title", widget: "string", default: "{{slug}}" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Active", name: "active", widget: "boolean" }


  - name: "events"
    label: "Event"
    folder: "_events/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Teaser_Image"
        name: "teaser_image"
        widget: "image"
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Active"
        name: "active"
        widget: "boolean"
        default: "false"

  - name: "rooms"
    label: "Rooms"
    folder: "_rooms/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string", default: "{{slug}}" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser Image", name: "teaser_image", widget: "image" }
      - { label: "Active", name: "active", widget: "boolean" }

