backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/images"
logo_url: "https://soalhouse.ca/assets/images/soal220.png"

collections:
  - name: "blog"
    label: "Post"
    folder: "_posts/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document. Specified in the front-matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/assets/images/blog/post1.jpg"
        media_library:
          config:
            multiple: true

  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    extension: "html"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "hidden", required: true }
      - { label: "Title", name: "title", widget: "string", default: {{name}}, required: true, hint: "Displayed in sidebar" }
      - { label: "URL", name: "permalink", widget: "string", required: true, default: "/", hint: "The URL this page will be found at." }
      - { label: "Priority", name: "priority", widget: "select", options: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],  default: "1", hint: "This is the relative order in which this page will appear on the sidebar. 1 = Highest, 9 - Lowest" }

  - name: "artist"
    label: "Artist"
    folder: "_artist/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Real Name"
        name: "real-name"
        required: false
      - label: "Bio"
        name: "bio"
        widget: "text"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Image 2"
        name: "image-2"
        widget: "image"
        required: false
      - label: "Image 3"
        name: "image-3"
        widget: "image"
        required: false
      - label: "Image 4"
        name: "image-4"
        widget: "image"
        required: false
      - label: "Image 5"
        name: "image-5"
        widget: "image"
        required: false

  - name: "gallery"
    label: "Gallery Exhibit"
    folder: "_gallery/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Artist"
        name: "artist"
        widget: "relation"
        collection: "artist"
        searchFields: ["name"]
        valueField: "name"
        displayFields: "name"
        required: true
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      - label: "Price"
        name: "price"
        widget: "string"
        default: ""
        required: false
      - label: "Images"
        name: "images"
        widget: "list"
        default: ["/assets/images/soal220.png"]
        allow_add: true
        required: true
        fields:
          - label: Image
            name: image
            widget: image
          - label: Caption
            name: caption
            widget: string
            required: false
  - name: "rooms"
    label: "Rooms"
    folder: "_rooms/"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Hidden", name: "hidden", widget: "boolean", required: true, default: false }
  - name: "content"
    label: "Content"
    files:
      - label: "About Page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Tennants
            name: tennants
            widget: list
            fields:
              - {label: Order, name: order, widget: number}
              - {label: Title, name: title, widget: string}
              - label: Description
                name: description
                widget: list
                required: false
                field: {label: Content, name: content, widget: string}
