backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow
# media_folder: "assets/_images"
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: soalhouse
    api_key: 947772475781272
    output_filename_only: true
    default_transformations:
      -   - fetch_format: auto
            width: auto:50
            gravity: auto
public_folder: "assets/images"
logo_url: "https://soalhouse.ca/assets/images/soal150.svg"

collections:
  - name: "gallery"
    label: "Exhibits"
    folder: "_gallery/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Artisans"
        name: "artisan"
        widget: "relation"
        collection: "artisan"
        searchFields: ["name"]
        valueField: "name"
        displayFields: "name"
        required: true
      - label: "Content"
        name: "Body"
        widget: "markdown"
        required: false
      - label: "Price"
        name: "price"
        widget: "number"
        default: ""
        required: false
      - label: "Stock"
        name: "stock"
        widget: "number"
        default: 1
        required: false
      - label: "Images"
        name: "images"
        widget: "list"
        default: ["/assets/images/soal220.png"]
        allow_add: true
        required: false
        fields:
          - label: Image
            name: image
            widget: image
            required: false
#   - name: "blog"
#     label: "Post"
#     folder: "_posts/"
#     create: true # Allow users to create new documents in this collection
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
#     fields: # The fields for each document. Specified in the front-matter
#       - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Category", name: "category", widget: "string"}
#       - {label: "Tags", name: "tags", widget: "string"}
#       - {label: "Summary", name: "summary", widget: "string"}
#       - label: "Image"
#         name: "image"
#         widget: "image"
#         default: "/assets/images/blog/post1.jpg"
#         media_library:
#           config:
#             multiple: true

  - name: "artisan"
    label: "Artisan"
    folder: "_artisan/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Excerpt"
        name: "excerpt"
        description: "140 (or less) characters to describe this person"
        widget: "string"
        required: false
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
  - name: "rooms"
    label: "Rooms"
    folder: "_rooms/"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Hidden", name: "hidden", widget: "boolean", required: true, default: false }
  - name: "settings"
    label: "Settings"
    files:
      - label: "Navigation"
        name: "sidebar_navigation"
        file: "_data/navigation.yml"
        fields:
          - label: Sidebar
            name: sidebar
            widget: list
            fields:
              - label: {Title, name: title, widget: string}
              - label: {URL, name: url, widget: string}

      - label: "About Page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - {label: List_Title, name: list_title, widget: string}
          - label: List_Entries
            name: list_entries
            widget: list
            field:
              - label: Entry
                name: entry
                widget: text
                required: false
