backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "blog"
    label: "Post"
    folder: "_posts/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document. Specified in the front-matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/assets/images/blog/post1.jpg"
        media_library:
          config:
            multiple: true

  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default", required: "false" }
      - { label: "Permalink", name: "permalink", widget: "string", default: "{{slug}}", required: "true" }
      - { label: "Title", name: "title", widget: "string", default: "{{slug}}", required: "true" }
      - { label: "Body", name: "body", widget: "markdown", default: "", required: "false" }
      - { label: "Priority", name: "priority", widget: "number", default: "", required: "false", default: 5 }

  - name: "artist"
    label: "Artist"
    folder: "_artist/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Bio"
        name: "bio"
        widget: "text"
        required: false

  - name: "gallery"
    label: "Art Gallery"
    folder: "_gallery/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Artist"
        name: "artist"
        widget: "relation"
        collection: "artist"
        searchFields: ["name"]
        valueField: "name"
        displayFields: "name"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Value"
        name: "value"
        widget: "string"
        default: ""
        required: false


  - name: "events"
    label: "Event"
    folder: "_events/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Teaser_Image"
        name: "teaser_image"
        widget: "image"
        required: "false"
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        required: "false"
      - label: "Description"
        name: "description"
        widget: "string"
        required: "true"
        default: ""
      - label: "Active"
        name: "active"
        widget: "boolean"
        default: "false"
        required: "false"

  - name: "rooms"
    label: "Room"
    folder: "_rooms/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string", default: "{{slug}}", required: "true" }
      - { label: "Description", name: "description", widget: "markdown", required: "false" }
      - { label: "Title", name: "title", widget: "string", default: "{{slug}}", required: "true" }
      - { label: "Teaser Image", name: "teaser_image", widget: "image", required: "false" }
      - { label: "Active", name: "active", widget: "boolean", required: "false", default: "false" }
      - { label: "Hidden", name: "hidden", widget: "boolean", required" true", default: "true" }

